### ISSUE TITLE
An error occured while unziping the 'CUHK-CQRC.zip'

### ISSUE THREAD

**Issue by June01** [cuhk-mobitec/HiQ-Robust-and-Fast-Decoding-of-High-Capacity-Color-QR-Codes#1]
Hey thanks for this nice work. I would like to download this dataset from [https://mobitec.ie.cuhk.edu.hk/authpaper/download.php](url), everything was fine at the begining, but not able to unzip in the end. I have tried to download and unzip in at least 3 devices, but no one works. So I am wondering what could be the reason for not being able to unzip? Is it possible for you guys to share another link or any convenient way? Thanks in advance, early response would be very much appreciated. :)

**Comment by SaneBow** [comment]
Hi June,

It sounds like the downloaded file is corrupted.
We've just switch to another more stable source, please try to download again and verify the MD5:

```bash
$ md5sum CUHK-CQRC.zip
875855dd41e34b2d20e63059b713c15f  CUHK-CQRC.zip 
```

**Comment by June01** [comment]
It works! Thanks for your hard-working. Have a nice weekend!
